// <auto-generated />
using System;
using GV23_Notice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GV23_Notice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306073029_addColumnsOnLogs")]
    partial class addColumnsOnLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GV23_Notice.Domain.Rolls.RollRegistry", b =>
                {
                    b.Property<int>("RollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LegacyRollId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceDb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RollId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.HasIndex("SourceDb", "IsActive");

                    b.ToTable("RollRegistry");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.CorrectionTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastEmailError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotifiedTo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestComment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId");

                    b.HasIndex("NoticeSettingsId", "Status");

                    b.HasIndex("RollId", "Notice", "Status");

                    b.ToTable("CorrectionTickets");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeApprovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId", "PerformedAtUtc");

                    b.ToTable("NoticeApprovalLogs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("BatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchKind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("BulkFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkToDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRecords")
                        .HasColumnType("int");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<int>("SettingsVersionUsed")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkflowKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex("NoticeSettingsId");

                    b.HasIndex("Roll", "Notice", "CreatedAtUtc");

                    b.ToTable("NoticeBatches");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticePreviewSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppealNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopyRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailBodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApprovedSnapshot")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int?>("NoticeBatchId")
                        .HasColumnType("int");

                    b.Property<int?>("NoticeRunLogId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PdfBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PremiseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<string>("UiMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("NoticePreviewSnapshots");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppealNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmlPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NoticeBatchId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectionNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PremiseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropertyDesc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticeBatchId", "Status");

                    b.ToTable("NoticeRunLogs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppealCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppealCloseOverrideAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppealCloseOverrideBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AppealCloseOverrideEvidencePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("AppealCloseOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ApprovalKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApprovedEmailSavedPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedEmailSentAtUtc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BatchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkToDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CityManagerSignDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrectionEmailSavedPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectionEmailSentAtUtc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnquiriesLine")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EvidenceCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtensionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtractPeriodDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExtractionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinancialYearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinancialYearStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinancialYearsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInvalidOmission")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSection52Review")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStep2Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LetterDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LetterDateOverridden")
                        .HasColumnType("bit");

                    b.Property<string>("LetterDateOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ObjectionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ObjectionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<string>("RollName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("Step2Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Step2ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Step2ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Step2ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step2ApprovedKeyVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Step2CorrectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Step2CorrectionRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Step2CorrectionRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Step2CorrectionRequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuationPeriodCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValuationPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValuationPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorkflowKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Roll", "Notice", "Mode", "Version")
                        .IsUnique();

                    b.HasIndex("Roll", "Notice", "Mode", "IsApproved", "ApprovedAtUtc");

                    b.ToTable("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeStep2CorrectionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailBodyHtmlSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubjectSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PdfSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJsonSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variant")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NoticeStep2CorrectionRequests");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeStep2Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailBodyHtmlSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubjectSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PdfSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJsonSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variant")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NoticeStep2Snapshots");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeTemplateApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId");

                    b.ToTable("NoticeTemplateApprovals");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeWorkflowAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("MetaJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId", "Action");

                    b.ToTable("NoticeWorkflowAuditLogs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.S49BatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchRunId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsSplit")
                        .HasColumnType("bit");

                    b.Property<string>("PremiseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BatchRunId", "PremiseId")
                        .IsUnique();

                    b.ToTable("S49BatchItems", (string)null);
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.S49BatchRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("PickedPremiseCount")
                        .HasColumnType("int");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TargetSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId", "BatchName")
                        .IsUnique();

                    b.ToTable("S49BatchRuns", (string)null);
                });

            modelBuilder.Entity("GV23_Notice.Models.DTOs.NoticeSettingsAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SettingsId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("NoticeSettingsAudits");
                });

            modelBuilder.Entity("GV23_Notice.Models.DTOs.S49BatchPickRow", b =>
                {
                    b.Property<string>("PremiseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("GV23_Notice.Models.DTOs.S49PendingCountDto", b =>
                {
                    b.Property<int>("PendingPremiseCount")
                        .HasColumnType("int");

                    b.Property<int>("PendingRowCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.CorrectionTicket", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany()
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeApprovalLog", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany("Batches")
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticePreviewSnapshot", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeRunLog", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", "NoticeBatch")
                        .WithMany("Runs")
                        .HasForeignKey("NoticeBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeBatch");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeTemplateApproval", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany()
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeWorkflowAuditLog", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany()
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.S49BatchItem", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.S49BatchRun", "BatchRun")
                        .WithMany("Items")
                        .HasForeignKey("BatchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchRun");
                });

            modelBuilder.Entity("GV23_Notice.Models.DTOs.NoticeSettingsAudit", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Batches");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.S49BatchRun", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
