// <auto-generated />
using System;
using GV23_Notice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GV23_Notice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216102822_AddRollRegistryTable")]
    partial class AddRollRegistryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GV23_Notice.Domain.Rolls.RollRegistry", b =>
                {
                    b.Property<int>("RollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LegacyRollId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceDb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RollId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.HasIndex("SourceDb", "IsActive");

                    b.ToTable("RollRegistry");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.CorrectionTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastEmailError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotifiedTo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId", "Status");

                    b.ToTable("CorrectionTickets");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeApprovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeSettingsId", "PerformedAtUtc");

                    b.ToTable("NoticeApprovalLogs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("BulkFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkToDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<int>("NoticeSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<int>("SettingsVersionUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex("NoticeSettingsId");

                    b.HasIndex("Roll", "Notice", "CreatedAtUtc");

                    b.ToTable("NoticeBatches");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppealNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmlPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NoticeBatchId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectionNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PremiseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticeBatchId", "Status");

                    b.ToTable("NoticeRunLogs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppealCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppealCloseOverrideAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppealCloseOverrideBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AppealCloseOverrideEvidencePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("AppealCloseOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("BatchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BulkToDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CityManagerSignDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnquiriesLine")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EvidenceCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtensionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtractPeriodDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExtractionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LetterDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LetterDateOverridden")
                        .HasColumnType("bit");

                    b.Property<string>("LetterDateOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Notice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ObjectionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ObjectionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<int>("RollId")
                        .HasColumnType("int");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Roll", "Notice", "Mode", "Version")
                        .IsUnique();

                    b.HasIndex("Roll", "Notice", "Mode", "IsApproved", "ApprovedAtUtc");

                    b.ToTable("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.CorrectionTicket", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany()
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeApprovalLog", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", "NoticeSettings")
                        .WithMany("Batches")
                        .HasForeignKey("NoticeSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NoticeSettings");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeRunLog", b =>
                {
                    b.HasOne("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", "NoticeBatch")
                        .WithMany("Runs")
                        .HasForeignKey("NoticeBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeBatch");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeBatch", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("GV23_Notice.Domain.Workflow.Entities.NoticeSettings", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
