using GV23_Notice.Domain.Workflow.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace GV23_Notice.Services.ThirdPartyApplications
{
    public sealed class ThirdPartyAppealFormalNoticePdfService : IThirdPartyAppealFormalNoticePdfService
    {
        private readonly IWebHostEnvironment _env;

        public ThirdPartyAppealFormalNoticePdfService(IWebHostEnvironment env)
        {
            _env = env;
        }

        public byte[] BuildPdf(
            NoticeSettings settings,
            ThirdPartyAppealApplicationNotice notice)
        {
            if (settings == null)
                throw new ArgumentNullException(nameof(settings));

            if (notice == null)
                throw new ArgumentNullException(nameof(notice));

            QuestPDF.Settings.License = LicenseType.Community;

            var letterDate = notice.LetterDate ?? DateTime.Today;

            var rollDisplayName = FirstNonEmpty(
     settings.RollName,
     notice.ValuationPeriod,
     settings.ValuationPeriodCode,
     "GENERAL VALUATION ROLL 2023");

            var responseDays = 30;

            var headerPath = ResolveHeaderImagePath();

            var title12 = TextStyle.Default.FontFamily("Arial").FontSize(12).SemiBold();
            var body9 = TextStyle.Default.FontFamily("Arial").FontSize(9);
            var body9b = TextStyle.Default.FontFamily("Arial").FontSize(9).SemiBold();
            var body10b = TextStyle.Default.FontFamily("Arial").FontSize(10).SemiBold();

            var value9 = TextStyle.Default.FontFamily("Arial").FontSize(9).SemiBold().FontColor(Colors.Black);
            var value10b = TextStyle.Default.FontFamily("Arial").FontSize(10).SemiBold().FontColor(Colors.Black);
            var muted9 = TextStyle.Default.FontFamily("Arial").FontSize(9).FontColor(Colors.Grey.Darken3);


            var small7 = TextStyle.Default.FontFamily("Arial").FontSize(7).FontColor(Colors.Grey.Darken2);
            var footerRef7 = TextStyle.Default.FontFamily("Arial").FontSize(7).SemiBold().FontColor(Colors.Grey.Darken3);

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(8);
                    page.MarginBottom(8);
                    page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(9f));

                    page.Footer()
                        .PaddingTop(8)
                        .AlignCenter()
                        .Text(t =>
                        {
                            t.Line("_______________________________________________").Style(small7);
                            t.Line("This is an official document generated by the City of Johannesburg Valuation Appeal Board")
                                .Style(small7);
                            t.Line($"Generated on: {letterDate:dd MMMM yyyy}")
                                .Style(small7);
                            t.Line(FirstNonEmpty(notice.Appeal_No, notice.Objection_No, notice.Valuation_Key, "")).Style(footerRef7);
                        });

                    page.Content().Column(col =>
                    {
                        col.Spacing(5);

                        AddHeaderImage(col, headerPath, body9b);

                        col.Item().PaddingTop(6);

                        col.Item().Row(r =>
                        {
                            r.RelativeItem().Column(left =>
                            {
                                left.Item().Element(c =>
                                    BuildFormalAddress(
                                        c,
                                        "TO:",
                                        BuildOwnerAddressLines(notice),
                                        body10b,
                                        value9));

                                left.Item().PaddingTop(3).Element(c =>
                                    BuildFormalAddress(
                                        c,
                                        "Cc:",
                                        BuildThirdPartyAddressLines(notice),
                                        body10b,
                                        value9));
                            });

                            r.ConstantItem(170)
                                .AlignRight()
                                .Text(t =>
                                {
                                    t.Span("DATE: ").Style(body10b);
                                    t.Span(letterDate.ToString(
                                            "dd MMMM yyyy",
                                            CultureInfo.GetCultureInfo("en-ZA")))
                                        .Style(value9);
                                });
                        });

                        col.Item().PaddingTop(10).Text("Dear Property Owner,").Style(body9b);

                        col.Item().PaddingTop(5).AlignCenter().Text(t =>
                        {
                            t.Span("NOTICE TO PROPERTY OWNER OF THIRD-PARTY APPEAL APPLICATION TO THE VALUATION APPEAL BOARD ")
                                .Style(title12);
                            t.Span(rollDisplayName.ToUpperInvariant()).Style(title12);

                        });

                        col.Item().PaddingTop(6).Text(t =>
                        {
                            t.Span("This letter serves to formally notify you that an appeal has been lodged by ")
                                .Style(body9);
                            t.Span(BuildDelegatedThirdPartyText(notice)).Style(value9);
                            t.Span(" concerning the municipal property valuation of your property namely, ")
                                .Style(body9);
                            t.Span(Display(notice.Property_Description)).Style(value9);
                            t.Span(".").Style(body9);
                        });

                        col.Item().Text(t =>
                        {
                            t.Span("The appeal was lodged by the third party, ")
                                .Style(body9);
                            t.Span(BuildThirdPartyIdentityText(notice)).Style(value9);
                            t.Span(" on the ")
                                .Style(body9);
                            t.Span(FormatDate(notice.DateAdded)).Style(value9);
                            t.Span(" in terms of section 54 of the Municipal Property Rates Act, 2004 (as amended), following an objection contemplated in section 50(1)(c) of the Act, which permits a person other than the owner to object to the property valuation.")
                                .Style(body9);
                        });

                        col.Item().PaddingTop(5).Element(e => BuildPropertyDetailsTable(e, notice, rollDisplayName));

                        col.Item().PaddingTop(6).Text("Reasons for Appeal by the third party are the following:")
                            .Style(body9b);

                        col.Item().Element(e => BuildReasonBox(e, notice.AppReason));

                        col.Item().PaddingTop(5).LineHorizontal(1).LineColor(Colors.Grey.Darken1);

                        col.Item().PaddingTop(7).Text("Third-party submission relevant to this appeal application and supporting documents are attached for your consideration.")
                            .Style(body9)
                            .Justify();



                        col.Item().PaddingTop(7).Text(t =>
                        {
                            t.Span("Upon consideration as mentioned above, you are hereby requested to electronically file submissions to the VAB Secretariat within ")
                                .Style(body9);
                            t.Span($"{responseDays} calendar days").Style(body9b);
                            t.Span(". Details of electronic filing are ")
                                .Style(body9);
                            t.Span("valuationenquiries@joburg.org.za").Style(value9);
                            t.Span(" and ")
                                .Style(body9);
                            t.Span(Display(notice.AdminEmail)).Style(value9);
                            t.Span(", alternatively physically file at COJ offices, 1st Floor East Wing, Jorissen Place, 66 Jorissen Street, Braamfontein.")
                                .Style(body9);
                        });

                        col.Item().PaddingTop(5).Text(t =>
                        {
                            t.Span("The appeal hearing shall be held on ")
                                .Style(body9);
                            t.Span(FormatDate(notice.ScheduleDate ?? notice.HearingDate)).Style(value9);
                            t.Span(" virtually via Microsoft Teams, meeting link will be sent to you to join the meeting should you so wish. This is a further invitation for you to inform the COJ secretariat within 7 days before the hearing date of your intention to attend the hearing and make oral representations at the Valuation Appeal Board hearing.")
                                .Style(body9);
                        });

                        col.Item().PaddingTop(5).Text("Please take note that the hearing shall proceed as scheduled, regardless of your contribution and/or adherence to the above procedure.")
                            .Style(body9)
                            .Justify();

                        col.Item().PaddingTop(5).Text(t =>
                        {
                            t.Span("For enquiries kindly contact ").Style(body9);
                            t.Span("valuationenquiries@joburg.org.za").Style(value9);
                        });

                        col.Item().PaddingTop(7).Text("Regards,").Style(body9);

                        col.Item().PaddingTop(14).Text("Valuation Appeal Board Secretariat").Style(body9);


                    });
                });
            }).GeneratePdf();
        }

        private void AddHeaderImage(ColumnDescriptor col, string headerPath, TextStyle body9b)
        {
            if (!string.IsNullOrWhiteSpace(headerPath) && File.Exists(headerPath))
            {
                col.Item().Image(headerPath, ImageScaling.FitWidth);
                return;
            }

            col.Item()
                .Border(1)
                .Padding(6)
                .Background(Colors.Grey.Lighten4)
                .Text(t =>
                {
                    t.Span("HEADER IMAGE NOT FOUND").Style(body9b);
                    t.Line($"Expected: {headerPath}");
                    t.Line($"WebRoot: {_env.WebRootPath ?? "(null)"}");
                });
        }

        private static void BuildPropertyDetailsTable(
      IContainer container,
      ThirdPartyAppealApplicationNotice notice,
      string rollDisplayName)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(150);
                    c.RelativeColumn();
                    c.RelativeColumn();
                    c.RelativeColumn();
                });

                t.Header(h =>
                {
                    h.Cell().Element(HeaderCell).Text("Property Details")
                        .FontFamily("Arial").FontSize(9).SemiBold();

                    h.Cell().Element(HeaderCell).Text($"Entry {BuildRollHeader(rollDisplayName)} Value")
                        .FontFamily("Arial").FontSize(9).SemiBold();

                    h.Cell().Element(HeaderCell).Text($"Objection Outcome[{Display(notice.Objection_No)}]")
                        .FontFamily("Arial").FontSize(9).SemiBold();

                    h.Cell().Element(HeaderCell).Text($"Appellant Request[{Display(notice.Appeal_No)}]")
                        .FontFamily("Arial").FontSize(9).SemiBold();
                });

                DataRow(
                    t,
                    "Property Market Value/\nProperty Valuation",
                    FormatRand(notice.RollMarketValue1),
                    FormatRand(notice.ObjectionOutcomeMarketValue1),
                    FormatRand(notice.AppellantRequestMarketValue1));

                DataRow(
                    t,
                    "Category",
                    SafeText(notice.RollCategory1),
                    SafeText(notice.ObjectionOutcomeCategory1),
                    SafeText(notice.AppellantRequestCategory1));

                DataRow(
                    t,
                    "Extent",
                    FormatExtent(notice.RollExtent1),
                    FormatExtent(notice.ObjectionOutcomeExtent1),
                    FormatExtent(notice.AppellantRequestExtent1));

                if (notice.IsMultipurpose)
                {
                    EmptyRow(t);

                    DataRow(
                        t,
                        "Property Market Value Split 1",
                        FormatRand(notice.RollMarketValue2),
                        FormatRand(notice.ObjectionOutcomeMarketValue2),
                        FormatRand(notice.AppellantRequestMarketValue2));

                    DataRow(
                        t,
                        "Category Split 1",
                        SafeText(notice.RollCategory2),
                        SafeText(notice.ObjectionOutcomeCategory2),
                        SafeText(notice.AppellantRequestCategory2));

                    DataRow(
                        t,
                        "Extent Split 1",
                        FormatExtent(notice.RollExtent2),
                        FormatExtent(notice.ObjectionOutcomeExtent2),
                        FormatExtent(notice.AppellantRequestExtent2));

                    EmptyRow(t);

                    DataRow(
                        t,
                        "Property Market Value Split 2",
                        FormatRand(notice.RollMarketValue3),
                        FormatRand(notice.ObjectionOutcomeMarketValue3),
                        FormatRand(notice.AppellantRequestMarketValue3));

                    DataRow(
                        t,
                        "Category Split 2",
                        SafeText(notice.RollCategory3),
                        SafeText(notice.ObjectionOutcomeCategory3),
                        SafeText(notice.AppellantRequestCategory3));

                    DataRow(
                        t,
                        "Extent Split 2",
                        FormatExtent(notice.RollExtent3),
                        FormatExtent(notice.ObjectionOutcomeExtent3),
                        FormatExtent(notice.AppellantRequestExtent3));
                }
            });

            static void DataRow(
                TableDescriptor t,
                string label,
                string? roll,
                string? objection,
                string? appellant)
            {
                t.Cell().Element(LabelCell).Text(label)
                    .FontFamily("Arial").FontSize(9).SemiBold();

                t.Cell().Element(ValueCell).Text(roll ?? "")
                    .FontFamily("Arial").FontSize(9);

                t.Cell().Element(ValueCell).Text(objection ?? "")
                    .FontFamily("Arial").FontSize(9);

                t.Cell().Element(ValueCell).Text(appellant ?? "")
                    .FontFamily("Arial").FontSize(9);
            }

            static void EmptyRow(TableDescriptor t)
            {
                t.Cell().Element(CellBase).Text("");
                t.Cell().Element(CellBase).Text("");
                t.Cell().Element(CellBase).Text("");
                t.Cell().Element(CellBase).Text("");
            }
        }

        private static void BuildReasonBox(
            IContainer container,
            string? reason)
        {
            var cleanReason = string.Join(
                Environment.NewLine,
                SplitReason(reason));

            container
                .Border(0.8f)
                .BorderColor(Colors.Grey.Darken2)
                .MinHeight(48)
                .PaddingVertical(5)
                .PaddingHorizontal(5)
                .Text(string.IsNullOrWhiteSpace(cleanReason)
                    ? " "
                    : cleanReason)
                .FontFamily("Arial")
                .FontSize(8.7f)
                .SemiBold()
                .FontColor(Colors.Black);
        }

        private static IEnumerable<string> SplitReason(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
                yield break;

            foreach (var part in value
                         .Replace("\r", "\n")
                         .Split('\n', StringSplitOptions.RemoveEmptyEntries))
            {
                var clean = part.Trim();

                if (!string.IsNullOrWhiteSpace(clean))
                    yield return clean;
            }
        }

        private string ResolveHeaderImagePath()
        {
            var candidates = new[]
            {
                Path.Combine(_env.WebRootPath ?? "", "Images", "Obj_Header.PNG"),
                Path.Combine(_env.WebRootPath ?? "", "images", "Obj_Header.PNG"),
                Path.Combine(_env.WebRootPath ?? "", "img", "Obj_Header.PNG"),
                Path.Combine(_env.WebRootPath ?? "", "Images", "Obj_Header.png"),
                Path.Combine(_env.WebRootPath ?? "", "images", "Obj_Header.png"),
                Path.Combine(_env.WebRootPath ?? "", "img", "Obj_Header.png")
            };

            return candidates.FirstOrDefault(File.Exists) ?? candidates[0];
        }

        private static IContainer HeaderCell(IContainer c) =>
            c.Border(0.8f)
             .BorderColor(Colors.Grey.Darken2)
             .Background(Colors.Grey.Lighten3)
             .PaddingVertical(5)
             .PaddingHorizontal(4);

        private static IContainer LabelCell(IContainer c) =>
            c.Border(0.8f)
             .BorderColor(Colors.Grey.Darken2)
             .Background(Colors.Grey.Lighten4)
             .PaddingVertical(5)
             .PaddingHorizontal(4);

        private static IContainer ValueCell(IContainer c) =>
            c.Border(0.8f)
             .BorderColor(Colors.Grey.Darken2)
             .PaddingVertical(5)
             .PaddingHorizontal(4);

        private static IContainer CellBase(IContainer c) =>
            c.Border(0.8f)
             .BorderColor(Colors.Grey.Darken2)
             .PaddingVertical(5)
             .PaddingHorizontal(4);

        private static string BuildRollHeader(string valuationPeriod)
        {
            var v = valuationPeriod.Trim();

            if (v.Contains("2023", StringComparison.OrdinalIgnoreCase))
                return "2023 General Valuation Roll";

            if (v.Contains("GENERAL VALUATION", StringComparison.OrdinalIgnoreCase))
                return v;

            return v;
        }

        private static void BuildFormalAddress(
            IContainer container,
            string label,
            IReadOnlyList<string> lines,
            TextStyle labelStyle,
            TextStyle valueStyle)
        {
            container.Row(row =>
            {
                row.ConstantItem(28)
                    .Text(label)
                    .Style(labelStyle);

                row.RelativeItem()
                    .Column(column =>
                    {
                        if (lines.Count == 0)
                        {
                            column.Item().Text("—").Style(valueStyle);
                            return;
                        }

                        foreach (var line in lines)
                        {
                            column.Item()
                                .Text(line)
                                .Style(valueStyle);
                        }
                    });
            });
        }

        private static IReadOnlyList<string> BuildOwnerAddressLines(
            ThirdPartyAppealApplicationNotice n)
        {
            return BuildAddressLines(
                n.OwnerName,
                n.OwnerAddress1,
                n.OwnerAddress2,
                n.OwnerAddress3,
                n.OwnerAddress4,
                n.OwnerAddress5);
        }

        private static IReadOnlyList<string> BuildThirdPartyAddressLines(
            ThirdPartyAppealApplicationNotice n)
        {
            return BuildAddressLines(
                n.ThirdPartyName,
                n.ThirdPartyAddress1,
                n.ThirdPartyAddress2,
                n.ThirdPartyAddress3,
                n.ThirdPartyAddress4,
                n.ThirdPartyAddress5);
        }

        private static IReadOnlyList<string> BuildAddressLines(
            params string?[] values)
        {
            return values
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .Select(x => x!.Trim().Trim(','))
                .Where(x => x.Length > 0)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static string BuildDelegatedThirdPartyText(
            ThirdPartyAppealApplicationNotice notice)
        {
            if (IsSihleMore(notice.ThirdPartyName))
            {
                return "Ms Sihle More delegated by City of Johannesburg Council";
            }

            return BuildThirdPartyWithStatus(notice);
        }

        private static string BuildThirdPartyIdentityText(
            ThirdPartyAppealApplicationNotice notice)
        {
            if (IsSihleMore(notice.ThirdPartyName))
            {
                return "City of Johannesburg – Ms Sihle More";
            }

            return BuildThirdPartyWithStatus(notice);
        }

        private static string BuildThirdPartyWithStatus(
            ThirdPartyAppealApplicationNotice notice)
        {
            var name = Display(notice.ThirdPartyName);
            var status = notice.Objector_Status?.Trim();

            return string.IsNullOrWhiteSpace(status)
                ? name
                : $"{name} ({status})";
        }

        private static bool IsSihleMore(string? name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return false;
            }

            var normalised = new string(
                name
                    .Where(char.IsLetterOrDigit)
                    .Select(char.ToUpperInvariant)
                    .ToArray());

            return normalised == "SIHLEMORE"
                || normalised == "MSSIHLEMORE"
                || normalised.EndsWith("SIHLEMORE", StringComparison.Ordinal);
        }

        private static string FirstNonEmpty(params string?[] values)
        {
            foreach (var value in values)
            {
                if (!string.IsNullOrWhiteSpace(value))
                    return value.Trim();
            }

            return "";
        }

        private static string Display(string? value)
            => string.IsNullOrWhiteSpace(value) ? "—" : value.Trim();

        private static string SafeText(string? value)
            => string.IsNullOrWhiteSpace(value) ? "" : value.Trim();

        private static string FormatDate(DateTime? value)
            => value.HasValue
                ? value.Value.ToString("d MMMM yyyy", CultureInfo.GetCultureInfo("en-ZA"))
                : "—";

        private static string FormatRand(object? value)
        {
            if (value is null)
                return "";

            var raw = value.ToString()?.Trim() ?? "";

            if (raw.Length == 0)
                return "";

            raw = raw.Replace("R", "", StringComparison.OrdinalIgnoreCase)
                     .Replace(",", "")
                     .Trim();

            raw = new string(raw.Where(ch => char.IsDigit(ch) || ch == '.' || ch == '-').ToArray());

            if (decimal.TryParse(raw, NumberStyles.Any, CultureInfo.InvariantCulture, out var amount))
                return "R " + amount.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

            return value.ToString()?.Trim() ?? "";
        }

        private static string FormatExtent(object? value)
        {
            if (value is null)
                return "";

            var raw = value.ToString()?.Trim() ?? "";

            if (raw.Length == 0)
                return "";

            raw = raw.Replace(",", "").Trim();

            if (decimal.TryParse(raw, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed))
            {
                if (parsed == Math.Truncate(parsed))
                    return parsed.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");

                return parsed.ToString("N2", CultureInfo.InvariantCulture).Replace(",", " ");
            }

            return value.ToString()?.Trim() ?? "";
        }
    }
}