using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace GV23_Notice.Services.Notices.Section49
{
    public sealed class Section49PdfBuilder : ISection49PdfBuilder
    {
        public byte[] BuildNotice(Section49PdfData data, Section49NoticeContext ctx)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            if (string.IsNullOrWhiteSpace(ctx.HeaderImagePath))
                throw new InvalidOperationException("HeaderImagePath is required for Section49 PDF.");

            var culture = CultureInfo.GetCultureInfo("en-ZA");

            var title12 = TextStyle.Default.FontFamily("Arial").FontSize(12).SemiBold();
            var sub10b = TextStyle.Default.FontFamily("Arial").FontSize(10).SemiBold();
            var body9 = TextStyle.Default.FontFamily("Arial").FontSize(9);
            var body9b = TextStyle.Default.FontFamily("Arial").FontSize(9).SemiBold();
            var small7 = TextStyle.Default.FontFamily("Arial").FontSize(7).FontColor(Colors.Grey.Darken2);



            var red7b = TextStyle.Default
                .FontFamily("Arial")
                .FontSize(7)
                .SemiBold()
                .FontColor(Colors.Red.Medium);


            var inspectionWindowText = ctx.ExtendedEndDate.HasValue
                ? $"{ctx.InspectionStartDate:dd MMMM yyyy} – {ctx.ExtendedEndDate:dd MMMM yyyy} until 15:00"
                : $"{ctx.InspectionStartDate:dd MMMM yyyy} – {ctx.InspectionEndDate:dd MMMM yyyy} until 15:00";

            var closingDate = ctx.ExtendedEndDate ?? ctx.InspectionEndDate;

            static string Safe(string? s) => string.IsNullOrWhiteSpace(s) ? "" : s.Trim();
            var recipient = Safe(data.Addr1);
            var greeting = string.IsNullOrWhiteSpace(recipient) ? "Dear Sir/Madam" : $"Dear: {recipient}";

            // rollDisplayName  – uppercased for headings  e.g. "SUPPLEMENTARY VALUATION ROLL 1"
            // rollDisplayTitle – proper case for body text e.g. "Supplementary Valuation Roll 1"
            var rollDisplayName = Safe(ctx.RollHeaderText).ToUpper();
            var rollDisplayTitle = Safe(ctx.RollHeaderText);
            // Ensure rows exist
            var rows = data.PropertyRows ?? new List<Section49PropertyRow>();
            if (rows.Count == 0)
            {
                // fallback row (should not happen if DB loader works)
                rows.Add(new Section49PropertyRow { Category = "", MarketValue = "", Extent = "", Remarks = "" });
            }

            // Force 4 rows for split/multipurpose
            if (data.ForceFourRows)
            {
                while (rows.Count < 4) rows.Add(new Section49PropertyRow());
                if (rows.Count > 4) rows = rows.Take(4).ToList();
            }

            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(10);
                    page.MarginBottom(10);

                    // ✅ FOOTER: bottom-left official text + bottom-right valuation key
                    page.Footer()
         .PaddingTop(8)
         .AlignCenter()
         .Text(t =>
         {
             t.Line("_______________________________________________").Style(small7);

             t.Line("This is an official document generated by the City of Johannesburg Valuation Services Department")
              .Style(small7);

             t.Line($"Generated on: {ctx.LetterDate:dd MMMM yyyy}")
              .Style(small7);

             t.Line(Safe(data.ValuationKey))
              .Style(red7b.SemiBold());
         });
                    page.Content().Column(col =>
                    {
                        col.Spacing(6);

                        // ===== HEADER IMAGE =====
                        col.Item().Image(ctx.HeaderImagePath, ImageScaling.FitWidth);

                        // ===== ADDRESS + DATE =====
                        col.Item().PaddingTop(6).Row(r =>
                        {
                            r.RelativeItem().Text(t =>
                            {
                                t.Span(Safe(data.Addr1) + "\n").Style(sub10b);

                                if (!string.IsNullOrWhiteSpace(data.Addr2)) t.Span(Safe(data.Addr2) + "\n").Style(sub10b);
                                if (!string.IsNullOrWhiteSpace(data.Addr3)) t.Span(Safe(data.Addr3) + "\n").Style(sub10b);
                                if (!string.IsNullOrWhiteSpace(data.Addr4)) t.Span(Safe(data.Addr4) + "\n").Style(sub10b);
                                if (!string.IsNullOrWhiteSpace(data.Addr5)) t.Span(Safe(data.Addr5) + "\n").Style(sub10b);
                            });

                            r.ConstantItem(180).AlignRight()
                                .Text(ctx.LetterDate.ToString("dd MMMM yyyy", culture))
                                .Style(body9);
                        });

                        // ===== TITLES =====
                        col.Item().AlignCenter().Text("CITY OF JOHANNESBURG").Style(title12);
                        col.Item().AlignCenter().Text(
                                       $"PUBLIC NOTICE CALLING FOR INSPECTION OF THE {rollDisplayName} AND LODGING OF OBJECTIONS"
                                   ).Style(sub10b);

                        col.Item().LineHorizontal(1.5f).LineColor(Colors.Grey.Darken2);
                        col.Item().PaddingBottom(6);

                        col.Item().PaddingTop(3).Text(greeting).FontFamily("Arial").FontSize(9).Bold();

                        // ===== MAIN NOTICE PARAGRAPH (mixed bold) =====
                        col.Item().Text(t =>
                        {
                            t.Span("Notice is hereby given in terms of Section 49(1)(a)(i) read together with section 78(2) of the ").Style(body9);
                            t.Span("Local Government: Municipal Property Rates Act No. 6 of 2004").Style(body9b);
                            t.Span($" as amended hereinafter referred to as the \"Act\", that the {Safe(ctx.RollHeaderText)} for the financial years ").Style(body9);
                            t.Span(Safe(ctx.FinancialYearsText)).Style(body9b);
                            t.Span(" is open for public inspection at the centre listed below, from ").Style(body9);
                            t.Span(inspectionWindowText).Style(body9b);
                            t.Span(". In addition, the valuation roll is available on the City's website ").Style(body9);
                            t.Span("www.joburg.org.za").Style(body9b);
                            t.Span(", under the GVR Online tile on the home page.\n").Style(body9);
                        });

                        col.Item().Text($"An invitation is hereby made in terms of section 49(1)(a)(ii) read together with section 78(2) of the Act to any owner of property or other person who so desires that may wish to lodge an objection with the Municipal Manager in respect of any matter reflected in, or omitted from, the {Safe(ctx.RollHeaderText)}. The objection must be submitted within the above mentioned inspection period."
                        ).Style(body9).Justify();

                        col.Item().Text(t =>
                        {
                            t.Span("Attention is specifically drawn to the fact that in terms of section 50(2) of the Act an objection must be in relation to a ").Style(body9);
                            t.Span("specific individual property").Style(body9b);
                            t.Span($" and not against the {Safe(ctx.RollHeaderText)} as such. The lodging of objections in terms of Chapter 4(d) of the Regulations to the Act can be done at the centre listed below or preferably online at ").Style(body9);
                            t.Span("www.joburg.org.za").Style(body9b);
                            t.Span(", under the GVR Online tile on the home page.").Style(body9);
                        });

                        col.Item().Text(
                            "The completed forms could be returned to the following address or preferably submitted online on the online objection system."
                        ).Style(body9);

                        col.Item().Background(Color.FromRGB(240, 240, 240))
                            .Padding(8)
                            .Column(box =>
                            {
                                box.Item().Text("Valuation Services: Administration").Style(body9b);
                                box.Item().Text("Jorissen Place, 66 Jorissen Street, Braamfontein, East Wing, 1st Floor").Style(body9);
                            });

                        col.Item().Text(
                                    "The acknowledgement letter will be generated by the online system and should be kept as proof that the objection was submitted."
                                ).Style(body9);

                        //// ===== PAGE BREAK =====
                        //col.Item().PageBreak();

                        // ===== PAGE 2 =====
                        col.Item().LineHorizontal(1.5f).LineColor(Colors.Grey.Darken2);

                        col.Item().AlignCenter().Text(
                            $"PROPERTY DETAILS AS LISTED IN {rollDisplayName}"
                        ).Style(sub10b);

                        // Property box (light blue-ish)
                        col.Item()
.Background(Color.FromRGB(245, 250, 255))
.Padding(8)
.Text(t =>
{
  t.Span("Property Description: ")
      .SemiBold()
      .Style(body9);

  t.Span(Safe(data.PropertyDesc))
      .Style(body9);

  t.EmptyLine();
  t.EmptyLine();
  t.Span("Physical Address: ")
      .SemiBold()
      .Style(body9);

  t.Span(Safe(data.PhysicalAddress))
      .Style(body9);
});
                        // Property table
                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(c =>
                            {
                                c.ConstantColumn(110); // Market Value
                                c.ConstantColumn(80);  // Extent
                                c.RelativeColumn();    // Category
                                c.RelativeColumn();    // Remarks
                            });

                            // Header cell helper
                            void HeaderCell(string text) =>
                                table.Cell().Background(Color.FromRGB(70, 130, 180))
                                    .PaddingVertical(4).PaddingHorizontal(4)
                                    .AlignCenter()
                                    .Text(text)
                                    .FontFamily("Arial").FontSize(8).SemiBold()
                                    .FontColor(Colors.White);
                            HeaderCell("Property Category");
                            HeaderCell("Area/m²");
                            HeaderCell("Market Value");


                            HeaderCell("With Effective Date");

                            // Row cell helper
                            void Cell(string? text, bool right = false, bool center = false)
                            {
                                var cell = table.Cell().Padding(4);

                                if (right) cell = cell.AlignRight();
                                else if (center) cell = cell.AlignCenter();

                                cell.Text(Safe(text)).FontFamily("Arial").FontSize(7);
                            }

                            // ✅ 4 rows already enforced above; just render them
                            foreach (var rr in rows)
                            {
                                Cell(rr.MarketValue, right: true);
                                Cell(rr.Extent, center: true);
                                Cell(rr.Category);
                                Cell(rr.Remarks);
                            }
                        });

                        // Closing date
                        col.Item().PaddingTop(10).AlignCenter().Text(
                            $"⚠ CLOSING DATE FOR OBJECTIONS IS 15:00 ON {closingDate:dd MMMM yyyy}"
                        ).Style(body9b);

                        // Signature (small + left aligned)
                        if (!string.IsNullOrWhiteSpace(ctx.SignaturePath) && File.Exists(ctx.SignaturePath))
                        {
                            col.Item().PaddingTop(10).AlignLeft().Width(180).Height(65)
                                .Image(ctx.SignaturePath, ImageScaling.FitArea);
                        }
                    });
                });
            });

            return doc.GeneratePdf();
        }
    }
}