using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace GV23_Notice.Services.Notices.Section78
{
    public sealed class Section78PdfBuilder : ISection78PdfBuilder
    {
        public byte[] BuildPreview(Section78PreviewData data, Section78PdfContext ctx)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            if (data is null) throw new ArgumentNullException(nameof(data));
            if (ctx is null) throw new ArgumentNullException(nameof(ctx));
            if (string.IsNullOrWhiteSpace(ctx.HeaderImagePath))
                throw new InvalidOperationException("HeaderImagePath is required for Section78 PDF.");

            var culture = CultureInfo.GetCultureInfo("en-ZA");

            var letterDateText = data.LetterDate.ToString("dd MMMM yyyy", culture);
            var reviewRangeText = $"{data.ReviewOpenDate:dd MMMM yyyy} – {data.ReviewCloseDate:dd MMMM yyyy}";
            var closeTimeText = $"{data.ReviewCloseDate:dd MMMM yyyy}";

            var websiteUrl = string.IsNullOrWhiteSpace(ctx.WebsiteUrl)
                ? "https://www.joburg.org.za"
                : ctx.WebsiteUrl.Trim();

            var enquiries1 = string.IsNullOrWhiteSpace(ctx.EnquiriesLine1) ? "Telephone 011 407-6622" : ctx.EnquiriesLine1.Trim();
            var enquiries2 = string.IsNullOrWhiteSpace(ctx.EnquiriesLine2) ? "Telephone 011 407-6597" : ctx.EnquiriesLine2.Trim();

            // Greeting name (like other builders): if you have owner name use it, else generic
            var recipientName = (data.OwnerName ?? "").Trim();
            var greeting = string.IsNullOrWhiteSpace(recipientName) ? "Dear Sir/Madam" : $"Dear {recipientName}";

            return Document.Create(doc =>
            {
                doc.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(10);
                    page.MarginBottom(10);

                    page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(11));

                    page.Footer().AlignCenter().Column(f =>
                    {
                        f.Item().PaddingTop(6).AlignCenter()
                            .Text("_______________________________________________")
                            .FontSize(7)
                            .FontColor(Colors.Grey.Darken2);

                        f.Item()
                            .Text("This is an official document generated by the City of Johannesburg Valuation Services Department")
                            .FontSize(7)
                            .AlignCenter()
                            .FontColor(Colors.Grey.Darken2);

                        f.Item()
                            .Text($"Generated on: {data.LetterDate:dd MMMM yyyy}")
                            .FontSize(7)
                            .AlignCenter()
                            .FontColor(Colors.Grey.Darken2);
                    });

                    page.Content().Column(col =>
                    {
                        // Header image (same pattern as other notices)
                        if (File.Exists(ctx.HeaderImagePath))
                            col.Item().Height(85).AlignCenter().Image(ctx.HeaderImagePath, ImageScaling.FitArea);

                        // Address block + date (same layout style)
                        col.Item().PaddingTop(10).Row(r =>
                        {
                            r.RelativeItem().Column(left =>
                            {
                                AddLine(left, data.OwnerName);
                                AddLine(left, data.PostalLine1);
                                AddLine(left, data.PostalLine2);
                                AddLine(left, data.PostalCode);
                            });

                            r.ConstantItem(200).AlignRight().Text(letterDateText).SemiBold();
                        });

                        // Heading
                        col.Item().PaddingTop(8)
                            .AlignCenter()
                            .Text("SECTION 78 NOTICE")
                            .SemiBold()
                            .FontSize(13);

                        col.Item().PaddingTop(6)
                            .AlignCenter()
                            .Text("NOTICE OF A SUPPLEMENTARY VALUATION TO THE GENERAL VALUATION ROLL 2023")
                            .Bold()
                            .FontSize(10);

                        col.Item().PaddingTop(6).LineHorizontal(1);

                        // Greeting
                        col.Item().PaddingTop(8).Text(greeting);

                        // Body paragraphs (kept as sentences, spacing by padding)
                        col.Item().PaddingTop(8).Text(
                            "Notice is hereby given in terms of Section 78(5)(a) read together with Section 78(5)(b) " +
                            "of the Local Government: Municipal Property Rates Act, 2004 (Act No. 6 of 2004), as amended, " +
                            "hereinafter referred to as the “Act”, that a Supplementary Valuation to the General Valuation Roll " +
                            "for the property described below has been completed."
                        ).Justify();

                        col.Item().PaddingTop(8).Text(
                            "An invitation is hereby made in terms of Section 78(5)(b) of the Act that any owner of the property who " +
                            "so desires may request a review with the Municipal Manager in respect of any matter reflected in the " +
                            $"supplementary valuation within the period: {reviewRangeText}."
                        ).Justify();

                        col.Item().PaddingTop(8).Text("The form for the lodging of a review is obtainable from the City's website:");
                        col.Item().PaddingTop(2).Text(t =>
                        {
                            // If you want, QuestPDF supports hyperlinks:
                            // t.Hyperlink(websiteUrl, websiteUrl).FontColor(Colors.Blue.Medium);
                            // But to keep it consistent and safe:
                            t.Span(websiteUrl).FontColor(Colors.Blue.Medium);
                        });

                        col.Item().PaddingTop(6).Text(
                            "or at the following address: Valuation Services: Administration, 1st Floor, East Wing, " +
                            "Jorissen Place, 66 Jorissen Street, Braamfontein."
                        ).Justify();

                        col.Item().PaddingTop(8).Text(
                            $"The completed review forms should be emailed to valuationenquiries@joburg.org.za or by hand to the " +
                            $"Valuation Services: Administration office on or before 15:00 on {closeTimeText}."
                        ).Justify();

                        col.Item().PaddingTop(6).Text("If a representative is appointed, proof of authorisation must be attached to this form.");

                        // Property section
                        col.Item().PaddingTop(10).Text("PROPERTY DETAILS THAT MAY BE REVIEWED:").SemiBold();

                        col.Item().PaddingTop(6).Text(t =>
                        {
                            t.Span("Property Description: ").SemiBold();
                            t.Span(data.PropertyDescription ?? "");
                        });

                        col.Item().PaddingTop(8).Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn();
                                c.RelativeColumn();
                                c.RelativeColumn();
                                c.RelativeColumn();
                            });

                            HeaderCell(t, "Property Category");
                            HeaderCell(t, "Market Value");
                            HeaderCell(t, "Extent");
                            HeaderCell(t, "Effective Date");

                            BodyCell(t, data.PropertyCategory);
                            BodyCell(t, FormatRand(data.MarketValue, culture));
                            BodyCell(t, FormatNumber(data.Extent, culture));
                            BodyCell(t, data.EffectiveDate.ToString("yyyy/MM/dd", culture));
                        });

                        // Enquiries
                        col.Item().PaddingTop(10).Text("For further enquiries please contact:").SemiBold();
                        col.Item().PaddingTop(6).Row(r =>
                        {
                            r.ConstantItem(12).Text("•");
                            r.RelativeItem().Text(enquiries1);
                        });
                        col.Item().PaddingTop(4).Row(r =>
                        {
                            r.ConstantItem(12).Text("•");
                            r.RelativeItem().Text(enquiries2);
                        });

                        // Footer-like signature block (like other notices)
                        col.Item().PaddingTop(14).Column(sig =>
                        {
                            if (!string.IsNullOrWhiteSpace(data.PremiseId))
                                sig.Item().Text(data.PremiseId).AlignRight().FontSize(11);

                            sig.Item().PaddingTop(8).Text(string.IsNullOrWhiteSpace(data.MunicipalValuer)
                                ? "Municipal Valuer"
                                : data.MunicipalValuer);
                        });
                    });
                });
            }).GeneratePdf();

            static void AddLine(ColumnDescriptor col, string? line)
            {
                if (!string.IsNullOrWhiteSpace(line))
                    col.Item().Text(line.Trim()).FontSize(11);
            }

            static IContainer CellBase(IContainer c) =>
                c.Border(1).PaddingVertical(4).PaddingHorizontal(6);

            static void HeaderCell(TableDescriptor t, string text)
            {
                t.Cell().Element(CellBase)
                    .Background(Colors.Grey.Lighten3)
                    .Text(text)
                    .Bold()
                    .FontSize(10);
            }

            static void BodyCell(TableDescriptor t, string? text)
            {
                t.Cell().Element(CellBase)
                    .Text((text ?? "").Trim())
                    .FontSize(10);
            }

            static string FormatRand(decimal value, CultureInfo culture)
            {
                // Keep it consistent with other notices: "R " + grouped number, no decimals
                return "R " + value.ToString("N0", culture);
            }

            static string FormatNumber(decimal value, CultureInfo culture)
            {
                return value.ToString("N0", culture);
            }
        }
    }
}
