using GV23_Notice.Services.Notices.Section53.COJ_Notice_2026.Models.ViewModels.Section53;
using Microsoft.Extensions.Options;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace GV23_Notice.Services.Notices.Section53
{
    public sealed class Section53PdfService : ISection53PdfService
    {
        private readonly Section53PdfOptions _opt;
        private readonly IWebHostEnvironment _env;

        public Section53PdfService(IOptions<Section53PdfOptions> opt, IWebHostEnvironment env)
        {
            _opt = opt.Value;
            _env = env;
        }

        public byte[] BuildNoticePdf(Section53MvdRow row, DateOnly letterDate)
            => BuildNoticePdf(new List<Section53MvdRow> { row }, letterDate);

        public byte[] BuildNoticePdf(IReadOnlyList<Section53MvdRow> rows, DateOnly letterDate)
            => BuildPdf(rows, letterDate, isPreview: false);

        public byte[] BuildPreviewPdf(Section53MvdRow dummyRow, DateOnly letterDate)
            => BuildPdf(new List<Section53MvdRow> { dummyRow }, letterDate, isPreview: true);

        private byte[] BuildPdf(IReadOnlyList<Section53MvdRow> rows, DateOnly letterDate, bool isPreview)
        {
            if (rows == null || rows.Count == 0)
                throw new InvalidOperationException("No rows provided for Section 53 PDF.");

            QuestPDF.Settings.License = LicenseType.Community;

            var model = new Model(rows, letterDate, _opt, _env);

            static string Safe(string? s) => string.IsNullOrWhiteSpace(s) ? "" : s.Trim();

            var valuationKey = Safe(model.ValuationKey);

            var title12 = TextStyle.Default.FontFamily("Arial").FontSize(12).SemiBold();
            var body9 = TextStyle.Default.FontFamily("Arial").FontSize(9);
            var body9b = TextStyle.Default.FontFamily("Arial").FontSize(9).SemiBold();
            var small7 = TextStyle.Default.FontFamily("Arial").FontSize(7).FontColor(Colors.Grey.Darken2);
            var red7b = TextStyle.Default.FontFamily("Arial").FontSize(7).SemiBold().FontColor(Colors.Red.Medium);
            var recipient = Safe(model.Addr1);
            var greeting = string.IsNullOrWhiteSpace(recipient) ? "Dear Sir/Madam" : $"Dear {recipient}";
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(10);
                    page.MarginBottom(10);
                    page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(9));

                    page.Footer()
                        .PaddingTop(8)
                        .AlignCenter()
                        .Text(t =>
                        {
                            t.Line("_______________________________________________").Style(small7);

                            t.Line("This is an official document generated by the City of Johannesburg Valuation Services Department")
                                .Style(small7);

                            t.Line($"Generated on: {letterDate:dd MMMM yyyy}")
                                .Style(small7);

                            t.Line(Safe(valuationKey))
                                .Style(red7b);
                        });

                    page.Content().Column(col =>
                    {
                        col.Spacing(6);

                        var headerPath = model.HeaderImageAbsolutePath;

                        if (!string.IsNullOrWhiteSpace(headerPath) && File.Exists(headerPath))
                        {
                            col.Item().Image(headerPath, ImageScaling.FitWidth);
                            col.Item().PaddingTop(6);
                        }
                        else
                        {
                            col.Item()
                                .Border(1)
                                .Padding(6)
                                .Background(Colors.Grey.Lighten4)
                                .Text(t =>
                                {
                                    t.Span("HEADER IMAGE NOT FOUND").SemiBold();
                                    t.Line($"Relative: {model.HeaderImageRelativePath ?? "(null)"}");
                                    t.Line($"Absolute: {headerPath ?? "(null)"}");
                                    t.Line($"WebRoot: {_env.WebRootPath ?? "(null)"}");
                                });

                            col.Item().PaddingTop(2);
                        }

                        if (isPreview)
                        {
                            col.Item()
                                .Border(1)
                                .Padding(6)
                                .Background(Colors.Grey.Lighten4)
                                .AlignCenter()
                                .Text("TEMPLATE PREVIEW – FOR ADMIN APPROVAL")
                                .Style(body9b);

                            col.Item().PaddingTop(8);
                        }

                        col.Item().Row(r =>
                        {
                            r.RelativeItem().Column(left =>
                            {
                                AddAddrLine(left, model.Addr1);
                                AddAddrLine(left, model.Addr2);
                                AddAddrLine(left, model.Addr3);
                                AddAddrLine(left, model.Addr4);
                                AddAddrLine(left, model.Addr5);
                            });

                            r.ConstantItem(180).AlignRight()
                                .Text(model.LetterDate.ToString("dd MMMM yyyy", CultureInfo.GetCultureInfo("en-ZA")))
                                .Style(body9);
                        });

                        col.Item().PaddingTop(2);

                        col.Item().AlignCenter().Text("SECTION 51 NOTICE").Style(title12);

                        col.Item().AlignCenter()
                            .Text("Notification of outcome of objection in terms of section 53(1) of the Municipal Property Rates Act, No.6 of 2004 as amended")
                            .Style(body9b);

                        col.Item().PaddingTop(6).LineHorizontal(1.5f).LineColor(Colors.Grey.Darken2);
                        col.Item().PaddingTop(1);

                        col.Item().PaddingTop(1).Text(greeting).FontFamily("Arial").FontSize(9).Bold();

                        col.Item().PaddingTop(1);

                        col.Item().Text(t =>
                        {
                            t.Span("Notice is hereby given in terms of section 53(1) of the Municipal Property Rates Act No.6 of 2004 as amended, that the objection Nr. ")
                                .Style(body9);
                            t.Span(model.ObjectionNo).Style(body9b);
                            t.Span(" against the entry of the above property in or omitted from the valuation roll has been considered by the Municipal Valuer. ")
                                .Style(body9);
                            t.Span("After reviewing the objection and reasons provided therein and the submission of the owner if a submission was made, together with the available market information, ")
                                .Style(body9);
                            t.Span("the Municipal Valuer’s decision is as follows:")
                                .Style(body9);
                        });

                        col.Item().PaddingTop(0);
                        col.Item().Text(t =>
                        {
                            t.Span("Property Description: ").Style(body9b);
                            t.Span(model.PropertyDesc).Style(body9);
                        });

   
                        col.Item().PaddingTop(0);
                        col.Item().Element(e => BuildComparisonTable(e, model));

                        col.Item().PaddingTop(0);

                        col.Item().Text(t =>
                        {
                            t.Span("Section 52 Review: ").Style(body9b);
                            t.Span(model.Section52Review).Style(body9);
                        });

                        col.Item().PaddingTop(0);

                        col.Item().Text(
                                "Kindly note that in terms of Section 52 of the Municipal Property Rates Act No.6 of 2004 as amended, if the value has changed by more than 10% upwards or downwards, an automatic review by the Valuation Appeal Board will be conducted who may confirm, amend or revoke the decision.")
                            .Style(body9b)
                            .Justify();

                        col.Item().PaddingTop(0);

                        col.Item().Text("Right of Appeal").Style(body9b);

                        col.Item().PaddingTop(1).Text(t =>
                        {

                            t.Span("In terms of Section 54(1) an appeal to the Appeal Board against the above decision may be lodged in the prescribed manner online on the City’s online system on the following link: ")
                                .Style(body9);
                            t.Span(model.PortalUrl).Style(body9).Bold();
                            t.Span(" or at the following address: Valuation Services: Administration, 1st Floor, East Wing, Jorissen Place, 66 Jorissen Street, Braamfontein on or before 15:00 on ")
                                .Style(body9);
                            t.Span(model.AppealCloseDateText).Style(body9b);
                            t.Span(".").Style(body9);
                        });

                        col.Item().PaddingTop(1).Text(
                                "An acknowledgement letter will be provided and should be kept as proof that the appeal was submitted. Please include this notice when submitting your appeal for ease of reference. Kindly note that objections against issues other than the above (eg. Owners name, street address etc) are not dealt with as an objection, but will be forwarded to the relevant department as amended to the valuation roll in terms of the section 79 of above Act. If a representative is appointed, proof of authorisation must be attached to the appeal form.")
                            .Style(body9)
                            .Justify();

                        if (!string.IsNullOrWhiteSpace(model.ContactLine))
                            col.Item().PaddingTop(1).Text(model.ContactLine).Style(body9).Bold();

                        col.Item().PaddingTop(1).Text(model.MunicipalValuerName).Style(body9b);
                        col.Item().Text(model.MunicipalValuerTitle).Style(body9b);
                    });
                });
            }).GeneratePdf();
        }

        private static void BuildComparisonTable(IContainer container, Model m)
        {

            bool isMulti =
                !string.IsNullOrWhiteSpace(m.Gv_Market_Value2) ||
                !string.IsNullOrWhiteSpace(m.Gv_Extent2) ||
                !string.IsNullOrWhiteSpace(m.Gv_Category2) ||
                !string.IsNullOrWhiteSpace(m.Gv_Market_Value3) ||
                !string.IsNullOrWhiteSpace(m.Gv_Extent3) ||
                !string.IsNullOrWhiteSpace(m.Gv_Category3) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Market_Value2) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Extent2) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Category2) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Market_Value3) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Extent3) ||
                !string.IsNullOrWhiteSpace(m.Mvd_Category3);

            var gvValue = FormatRand(m.Gv_Market_Value);
            var gvValue1 = FormatRand(m.Gv_Market_Value2);
            var gvValue2 = FormatRand(m.Gv_Market_Value3);

            var gvExtent = FormatExtent(m.Gv_Extent);
            var gvExtent1 = FormatExtent(m.Gv_Extent2);
            var gvExtent2 = FormatExtent(m.Gv_Extent3);

            var gvCategory = SafeText(m.Gv_Category);
            var gvCategory1 = SafeText(m.Gv_Category2);
            var gvCategory2 = SafeText(m.Gv_Category3);

            var mvdValue = FormatRand(m.Mvd_Market_Value);
            var mvdValue1 = FormatRand(m.Mvd_Market_Value2);
            var mvdValue2 = FormatRand(m.Mvd_Market_Value3);

            var mvdExtent = FormatExtent(m.Mvd_Extent);
            var mvdExtent1 = FormatExtent(m.Mvd_Extent2);
            var mvdExtent2 = FormatExtent(m.Mvd_Extent3);

            var mvdCategory = SafeText(m.Mvd_Category);
            var mvdCategory1 = SafeText(m.Mvd_Category2);
            var mvdCategory2 = SafeText(m.Mvd_Category3);

            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(150);
                    c.RelativeColumn();
                    c.RelativeColumn();
                });

                t.Header(h =>
                {
                    h.Cell().Element(BlueHeaderCell).Text("");
                    h.Cell().Element(BlueHeaderCell).Text($"Entry in {m.RollName}")
     .FontFamily("Arial").FontSize(9).SemiBold().FontColor(Colors.White);
                    h.Cell().Element(BlueHeaderCell).Text("Municipal Valuer’s Decision (MVD)")
                        .FontFamily("Arial").FontSize(9).SemiBold().FontColor(Colors.White);
                });

                if (!isMulti)
                {
                    DataRow(t, "Category", gvCategory, mvdCategory);
                    DataRow(t, "Extent", gvExtent, mvdExtent);
                    DataRow(t, "Market Value", gvValue, mvdValue);
                    DataRow(t, "With Effective Date", "", "");

                }
                else
                {
                    DataRow(t, "Category", gvCategory, mvdCategory);
                    DataRow(t, "Category Split 1", gvCategory1, mvdCategory1);
                    DataRow(t, "Category Split 2", gvCategory2, mvdCategory2);

                    DataRow(t, "", "", "");


                    DataRow(t, "Extent", gvExtent, mvdExtent);
                    DataRow(t, "Extent Split 1", gvExtent1, mvdExtent1);
                    DataRow(t, "Extent Split 2", gvExtent2, mvdExtent2);

                    DataRow(t, "", "", "");

                    DataRow(t, "Market Value", gvValue, mvdValue);
                    DataRow(t, "Market Value Split 1", gvValue1, mvdValue1);
                    DataRow(t, "Market Value Split 2", gvValue2, mvdValue2);
                    DataRow(t, "With Effective Date", "", "");



                }
            });

            static void DataRow(TableDescriptor t, string label, string? left, string? right)
            {
                t.Cell().Element(CellBase).Text(label).FontFamily("Arial").FontSize(9).SemiBold();
                t.Cell().Element(CellBase).Text(left ?? "").FontFamily("Arial").FontSize(9);
                t.Cell().Element(CellBase).Text(right ?? "").FontFamily("Arial").FontSize(9);
            }

            static string SafeText(string? s) => string.IsNullOrWhiteSpace(s) ? "" : s.Trim();
        }
      
      
        private static string FormatRand(object? value)
        {
            if (value is null) return "";

            var raw = value.ToString()?.Trim() ?? "";
            if (raw.Length == 0) return "";

            raw = raw.Replace("R", "", StringComparison.OrdinalIgnoreCase)
                     .Replace(",", "")
                     .Trim();

            raw = new string(raw.Where(ch => char.IsDigit(ch) || ch == '.' || ch == '-').ToArray());

            if (decimal.TryParse(raw, NumberStyles.Any, CultureInfo.InvariantCulture, out var amount))
                return "R " + amount.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

            return value.ToString()?.Trim() ?? "";
        }

        private static string FormatExtent(object? value)
        {
            if (value is null) return "";

            var raw = value.ToString()?.Trim() ?? "";
            if (raw.Length == 0) return "";

            raw = raw.Replace(",", "").Trim();

            if (decimal.TryParse(raw, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed))
            {
                if (parsed == Math.Truncate(parsed))
                    return parsed.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");

                return parsed.ToString("N2", CultureInfo.InvariantCulture).Replace(",", " ");
            }

            return value.ToString()?.Trim() ?? "";
        }

        private static void AddAddrLine(ColumnDescriptor col, string? line)
        {
            if (!string.IsNullOrWhiteSpace(line))
                col.Item().Text(line.Trim()).FontFamily("Arial").FontSize(9);
        }

        private static IContainer CellBase(IContainer c) =>
            c.Border(1).PaddingVertical(4).PaddingHorizontal(6);

        private static IContainer BlueHeaderCell(IContainer c) =>
            c.Border(1)
             .Background(Color.FromRGB(70, 130, 180))
             .PaddingVertical(4)
             .PaddingHorizontal(6);

    

        private sealed record Model(IReadOnlyList<Section53MvdRow> Rows, DateOnly LetterDate, Section53PdfOptions Opt, IWebHostEnvironment Env)
        {
            private Section53MvdRow First => Rows[0];

            public string RollName => string.IsNullOrWhiteSpace(First.RollName) ? "Valuation Roll" : First.RollName!;
            public string? HeaderImageRelativePath => Opt.HeaderImageRelativePath;
            public string HeaderImageAbsolutePath => ResolveWwwRootPath(Env, Opt.HeaderImageRelativePath);

            public string PortalUrl => Opt.PortalUrl ?? "https://objections.joburg.org.za/";
            public string ContactLine => Opt.ContactLine ?? "";
            public string MunicipalValuerName => Opt.MunicipalValuerName ?? "S. Faiaz";
            public string MunicipalValuerTitle => Opt.MunicipalValuerTitle ?? "Municipal Valuer";

            public string ObjectionNo => First.ObjectionNo ?? "";
            public string PropertyDesc => First.PropertyDesc ?? "";

            public string Addr1 => First.Addr1 ?? "";
            public string Addr2 => First.Addr2 ?? "";
            public string Addr3 => First.Addr3 ?? "";
            public string Addr4 => First.Addr4 ?? "";
            public string Addr5 => First.Addr5 ?? "";

            public string ValuationKey => First.ValuationKey ?? "";
            public string Section52Review => First.Section52Review ?? "";

            public string AppealCloseDateText =>
                First.AppealCloseDate.HasValue
                    ? First.AppealCloseDate.Value.ToString("dd MMMM yyyy", CultureInfo.GetCultureInfo("en-ZA"))
                    : "";

            public string Gv_Market_Value => First.Gv_Market_Value ?? "";
            public string Gv_Market_Value2 => First.Gv_Market_Value2 ?? "";
            public string Gv_Market_Value3 => First.Gv_Market_Value3 ?? "";

            public string Gv_Extent => First.Gv_Extent ?? "";
            public string Gv_Extent2 => First.Gv_Extent2 ?? "";
            public string Gv_Extent3 => First.Gv_Extent3 ?? "";

            public string Gv_Category => First.Gv_Category ?? "";
            public string Gv_Category2 => First.Gv_Category2 ?? "";
            public string Gv_Category3 => First.Gv_Category3 ?? "";

            public string Mvd_Market_Value => First.Mvd_Market_Value ?? "";
            public string Mvd_Market_Value2 => First.Mvd_Market_Value2 ?? "";
            public string Mvd_Market_Value3 => First.Mvd_Market_Value3 ?? "";

            public string Mvd_Extent => First.Mvd_Extent ?? "";
            public string Mvd_Extent2 => First.Mvd_Extent2 ?? "";
            public string Mvd_Extent3 => First.Mvd_Extent3 ?? "";

            public string Mvd_Category => First.Mvd_Category ?? "";
            public string Mvd_Category2 => First.Mvd_Category2 ?? "";
            public string Mvd_Category3 => First.Mvd_Category3 ?? "";
        }

        private static string ResolveWwwRootPath(IWebHostEnvironment env, string? relativePath)
        {
            if (string.IsNullOrWhiteSpace(relativePath))
                return "";

            relativePath = relativePath.Trim().TrimStart('/', '\\');
            var parts = relativePath.Replace('\\', '/')
                                    .Split('/', StringSplitOptions.RemoveEmptyEntries);

            return Path.Combine(new[] { env.WebRootPath }.Concat(parts).ToArray());
        }
    }
}