using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;
using System.Text.RegularExpressions;

namespace GV23_Notice.Services.Notices.Section52
{
    public sealed class Section52PdfService : ISection52PdfService
    {
        private readonly IWebHostEnvironment _env;

        public Section52PdfService(IWebHostEnvironment env) => _env = env;

        // ✅ legacy compatibility
        public byte[] BuildDecisionPdf(AppealDecisionRow model, DateOnly letterDate)
        {
            var headerPath = Path.Combine(_env.WebRootPath ?? "", "Images", "Obj_Header.PNG");
            var ctx = new Section52PdfContext { HeaderImagePath = headerPath, LetterDate = letterDate };
            return BuildPdf(model, ctx, isPreview: false);
        }

        public byte[] BuildNotice(AppealDecisionRow row, Section52PdfContext ctx)
            => BuildPdf(row, ctx, isPreview: false);

        public byte[] BuildPreview(Section52PreviewData preview)
        {
            var row = new AppealDecisionRow
            {
                A_UserID = preview.IsReview ? "System_Generated" : "User",

                ADDR1 = preview.RecipientName,
                ADDR2 = "XXXX",
                ADDR3 = "XXXX",
                ADDR4 = "XXXX",
                ADDR5 = "XXXX",

                Email = preview.Email,
                Property_desc = preview.PropertyDescription,

                Town = preview.Town,
                ERF = preview.Erf,
                PTN = preview.Portion,
                RE = preview.Re,

                Objection_No = preview.ObjectionNo,
                Appeal_No = preview.AppealNo,

                App_Category = preview.Category,
                App_Extent = preview.Extent,
                App_Extent2 = preview.Extent2,
                App_Extent3 = preview.Extent3,

                App_Market_Value = preview.MarketValue,
                App_Market_Value2 = preview.MarketValue2,
                App_Market_Value3 = preview.MarketValue3,

                valuation_Key = preview.ValuationKey
            };

            var ctx = new Section52PdfContext
            {
                HeaderImagePath = preview.HeaderImagePath,
                LetterDate = preview.LetterDate
            };

            return BuildPdf(row, ctx, isPreview: true);
        }

        private static byte[] BuildPdf(AppealDecisionRow model, Section52PdfContext ctx, bool isPreview)
        {
            if (model is null) throw new ArgumentNullException(nameof(model));
            if (ctx is null) throw new ArgumentNullException(nameof(ctx));
            if (string.IsNullOrWhiteSpace(ctx.HeaderImagePath))
                throw new InvalidOperationException("HeaderImagePath is required for Section52 PDF.");

            static string Safe(string? s) => string.IsNullOrWhiteSpace(s) ? "" : s.Trim();

            var headerPath = ctx.HeaderImagePath;
            var isReview = string.Equals(model.A_UserID, "System_Generated", StringComparison.OrdinalIgnoreCase);

            var title = isReview
                ? "VALUATION APPEAL BOARD: OUTCOME - SECTION 52 REVIEWS DECISIONS FOR THE GENERAL VALUATION ROLL 2023 (GV2023)"
                : "VALUATION APPEAL BOARD: OUTCOME - APPEAL DECISIONS FOR THE GENERAL VALUATION ROLL 2023 (GV2023)";

            var kindShort = isReview ? "Section 52 Review" : "Appeal";

            var dateText = ctx.LetterDate
                .ToDateTime(TimeOnly.MinValue)
                .ToString("dd MMMM yyyy", CultureInfo.GetCultureInfo("en-ZA"));

            var recipient = Safe(model.ADDR1);
            var greeting = string.IsNullOrWhiteSpace(recipient) ? "Dear Sir/Madam" : $"Dear {recipient}";

            var sigName = "VALUATION APPEAL BOARD";
            var sigOrg = "City of Johannesburg";

            var valuationKey = Safe(model.valuation_Key);

            // ✅ Build resolved rows safely (up to 3)
            var resolvedRows = BuildResolvedRows(model);

            return Document.Create(doc =>
            {
                doc.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(10);
                    page.MarginBottom(10);

                    page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(9)); // ✅ align with other notices

                    // ✅ Footer: SAME as Section49/Section51
                    page.Footer().PaddingTop(8).Row(r =>
                    {
                        var small7 = TextStyle.Default.FontFamily("Arial").FontSize(7).FontColor(Colors.Grey.Darken2);

                        r.RelativeItem().AlignLeft().Text(t =>
                        {
                            t.Span("_______________________________________________\n").Style(small7);
                            t.Span("This is an official document generated by the City of Johannesburg Valuation Services Department\n").Style(small7);
                            t.Span($"Generated on: {DateTime.Now:dd MMMM yyyy}").Style(small7);
                        });

                        r.ConstantItem(220).AlignRight().Text(t =>
                        {
                            t.Span("Valuation Key:\n").Style(small7);
                            t.Span(valuationKey).Style(small7.SemiBold());
                        });
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(6);

                        // ✅ Preview banner (optional)
                        if (isPreview)
                        {
                            col.Item()
                               .Border(1)
                               .Background(Colors.Grey.Lighten3)
                               .Padding(6)
                               .AlignCenter()
                               .Text("TEMPLATE PREVIEW (DB / SAMPLE) – FOR ADMIN APPROVAL")
                               .FontFamily("Arial").FontSize(9).SemiBold();
                        }

                        // Header image (same approach as others)
                        if (File.Exists(headerPath))
                            col.Item().Image(headerPath, ImageScaling.FitWidth);

                        // Address block + date
                        col.Item().PaddingTop(6).Row(r =>
                        {
                            r.RelativeItem().Column(left =>
                            {
                                AddLine(left, model.ADDR1);
                                AddLine(left, model.ADDR2);
                                AddLine(left, model.ADDR3);
                                AddLine(left, model.ADDR4);
                                AddLine(left, model.ADDR5);

                                if (!string.IsNullOrWhiteSpace(model.Email))
                                {
                                    left.Item().PaddingTop(8);
                                    left.Item().Text(Safe(model.Email)).FontFamily("Arial").FontSize(9).SemiBold();
                                }
                            });

                            r.ConstantItem(180).AlignRight()
                                .Text(dateText)
                                .FontFamily("Arial").FontSize(9);
                        });

                        // Titles
                        col.Item().PaddingTop(8)
                            .AlignCenter()
                            .Text($"GV2023 {kindShort.ToUpperInvariant()} NOTICE")
                            .FontFamily("Arial").FontSize(12).SemiBold();

                        col.Item().AlignCenter()
                            .Text(title)
                            .FontFamily("Arial").FontSize(9).SemiBold();

                        col.Item().PaddingTop(6).LineHorizontal(1.5f).LineColor(Colors.Grey.Darken2);

                        col.Item().PaddingTop(8).Text(greeting).FontFamily("Arial").FontSize(9);

                        col.Item().PaddingTop(6).Text(
                            "With reference to the above matter, I wish to advise that the Valuation Appeal Board for the property description below:"
                        ).FontFamily("Arial").FontSize(9).Justify();

                        col.Item().PaddingTop(8).Text(t =>
                        {
                            t.Span("Property Description: ").FontFamily("Arial").FontSize(9).SemiBold();
                            t.Span(Safe(model.Property_desc)).FontFamily("Arial").FontSize(9);
                        });

                        // Property details table
                        col.Item().PaddingTop(8).Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(); // Suburb
                                c.RelativeColumn(); // ERF
                                c.RelativeColumn(); // Portion
                                c.RelativeColumn(); // RE
                                c.RelativeColumn(); // Objection
                                if (!isReview) c.RelativeColumn(); // Appeal No
                            });

                            HeaderCell(t, "SUBURB");
                            HeaderCell(t, "ERF NUMBER");
                            HeaderCell(t, "PORTION");
                            HeaderCell(t, "RE");
                            HeaderCell(t, "OBJECTION NO");
                            if (!isReview) HeaderCell(t, "APPEAL NO");

                            BodyCell(t, model.Town);
                            BodyCell(t, model.ERF);
                            BodyCell(t, model.PTN);
                            BodyCell(t, model.RE);
                            BodyCell(t, model.Objection_No);
                            if (!isReview) BodyCell(t, model.Appeal_No);
                        });

                        col.Item().PaddingTop(10).Text("Resolved inter alia as follows:")
                            .FontFamily("Arial").FontSize(9).SemiBold();

                        // Resolved table (dynamic rows)
                        col.Item().PaddingTop(6).Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn();
                                c.RelativeColumn();
                                c.RelativeColumn();
                            });

                            HeaderCell(t, "Property Category");
                            HeaderCell(t, "Area/m²");
                            HeaderCell(t, "Market Value");

                            foreach (var rr in resolvedRows)
                            {
                                BodyCell(t, rr.Category);
                                BodyCell(t, rr.Extent);
                                BodyCell(t, rr.MarketValue);
                            }

                            // optional: keep at least 1 body row
                            if (resolvedRows.Count == 0)
                            {
                                BodyCell(t, "");
                                BodyCell(t, "");
                                BodyCell(t, "");
                            }
                        });

                        col.Item().PaddingTop(10).Column(points =>
                        {
                            points.Item().Text("Please note the following:")
                                .FontFamily("Arial").FontSize(9).SemiBold();

                            Bullet(points, "The decision will be adjusted accordingly to the implementation date being 1 July 2023.");
                            Bullet(points,
                                "The decision will reflect on your account within 30 days. Any adjustments to the account, if applicable, " +
                                "will be made by the Rates and Taxes Department in due course.");
                            Bullet(points,
                                "If you feel aggrieved by the above decision, you are entitled to take the matter on review to the " +
                                "High Court of South Africa at your own cost.");

                            points.Item().PaddingTop(12).Text("Regards,")
                                .FontFamily("Arial").FontSize(9).SemiBold();
                        });

                        // Signature block (no valuation key here anymore)
                        col.Item().PaddingTop(14).Column(sig =>
                        {
                            sig.Item().Text(sigName).FontFamily("Arial").FontSize(9).SemiBold();
                            sig.Item().Text(sigOrg).FontFamily("Arial").FontSize(9);
                        });
                    });
                });
            }).GeneratePdf();

            // ---------- local helpers ----------
            static void AddLine(ColumnDescriptor col, string? line)
            {
                if (!string.IsNullOrWhiteSpace(line))
                    col.Item().Text(line.Trim()).FontFamily("Arial").FontSize(9);
            }

            static IContainer CellBase(IContainer c) => c.Border(1).PaddingVertical(4).PaddingHorizontal(6);

            static void HeaderCell(TableDescriptor t, string text)
            {
                t.Cell().Element(CellBase)
                    .Background(Colors.Grey.Lighten3)
                    .Text(text)
                    .FontFamily("Arial").FontSize(9).SemiBold();
            }

            static void BodyCell(TableDescriptor t, string? text)
            {
                t.Cell().Element(CellBase)
                    .Text((text ?? "").Trim())
                    .FontFamily("Arial").FontSize(9);
            }

            static void Bullet(ColumnDescriptor points, string text)
            {
                points.Item().PaddingTop(6).Row(r =>
                {
                    r.ConstantItem(12).Text("•").FontFamily("Arial").FontSize(9);
                    r.RelativeItem().Text(text).FontFamily("Arial").FontSize(9);
                });
            }

            static List<(string Category, string Extent, string MarketValue)> BuildResolvedRows(AppealDecisionRow m)
            {
                var rows = new List<(string, string, string)>();

                void Add(string? cat, object? extent, object? mv)
                {
                    var c = (cat ?? "").Trim();
                    var e = (extent?.ToString() ?? "").Trim();
                    var v = FormatRand(mv);

                    // if all empty, skip
                    if (string.IsNullOrWhiteSpace(c) && string.IsNullOrWhiteSpace(e) && string.IsNullOrWhiteSpace(v))
                        return;

                    rows.Add((c, e, v));
                }

                Add(m.App_Category, m.App_Extent, m.App_Market_Value);
                Add(m.App_Category2, m.App_Extent2, m.App_Market_Value2);
                Add(m.App_Category3, m.App_Extent3, m.App_Market_Value3);

                return rows;
            }

            static string FormatRand(object? value)
            {
                if (value is null) return "";

                if (value is decimal dec)
                    return "R " + dec.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

                if (value is double dbl)
                    return "R " + Convert.ToDecimal(dbl).ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

                if (value is int i)
                    return "R " + i.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

                if (value is long l)
                    return "R " + l.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

                var raw = value.ToString()?.Trim() ?? "";
                if (raw.Length == 0) return "";

                if (raw.StartsWith("R", StringComparison.OrdinalIgnoreCase))
                    raw = raw.Substring(1).Trim();

                // strip spaces, keep digits/.- 
                var cleaned = new string(raw.Where(ch => char.IsDigit(ch) || ch == '.' || ch == '-').ToArray());

                if (decimal.TryParse(cleaned, NumberStyles.Any, CultureInfo.InvariantCulture, out var amount))
                    return "R " + amount.ToString("#,##0", CultureInfo.InvariantCulture).Replace(",", " ");

                // fallback
                return "R " + raw;
            }
        }
    }
}
