using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;
using System.Text.RegularExpressions;

namespace GV23_Notice.Services.Notices.Section52
{
    public sealed class Section52PdfService : ISection52PdfService
    {
        private readonly IWebHostEnvironment _env;

        public Section52PdfService(IWebHostEnvironment env) => _env = env;

        // ✅ legacy compatibility
        public byte[] BuildDecisionPdf(AppealDecisionRow model, DateOnly letterDate)
        {
            var headerPath = Path.Combine(_env.WebRootPath ?? "", "Images", "Obj_Header.PNG");
            var ctx = new Section52PdfContext { HeaderImagePath = headerPath, LetterDate = letterDate };
            return BuildPdf(model, ctx, isPreview: false);
        }

        public byte[] BuildNotice(AppealDecisionRow row, Section52PdfContext ctx)
            => BuildPdf(row, ctx, isPreview: false);

        public byte[] BuildPreview(Section52PreviewData preview)
        {
            var row = new AppealDecisionRow
            {
                A_UserID = preview.IsReview ? "System_Generated" : "User",

                ADDR1 = preview.RecipientName,
                ADDR2 = "XXXX",
                ADDR3 = "XXXX",
                ADDR4 = "XXXX",
                ADDR5 = "XXXX",

                Email = preview.Email,

                Property_desc = preview.PropertyDescription,

                Town = preview.Town,
                ERF = preview.Erf,
                PTN = preview.Portion,
                RE = preview.Re,

                Objection_No = preview.ObjectionNo,
                Appeal_No = preview.AppealNo,

                App_Category = preview.Category,

                App_Extent = preview.Extent,
                App_Extent2 = preview.Extent2,
                App_Extent3 = preview.Extent3,

                App_Market_Value = preview.MarketValue,
                App_Market_Value2 = preview.MarketValue2,
                App_Market_Value3 = preview.MarketValue3,

                valuation_Key = preview.ValuationKey
            };

            var ctx = new Section52PdfContext
            {
                HeaderImagePath = preview.HeaderImagePath,
                LetterDate = preview.LetterDate
            };

            return BuildPdf(row, ctx, isPreview: true);
        }

        private static byte[] BuildPdf(AppealDecisionRow model, Section52PdfContext ctx, bool isPreview)
        {
            if (model is null) throw new ArgumentNullException(nameof(model));
            if (ctx is null) throw new ArgumentNullException(nameof(ctx));

            var headerPath = ctx.HeaderImagePath ?? "";

            var isReview = string.Equals(model.A_UserID, "System_Generated", StringComparison.OrdinalIgnoreCase);

            var title = isReview
                ? "VALUATION APPEAL BOARD: OUTCOME - SECTION 52 REVIEWS DECISIONS FOR THE GENERAL VALUATION ROLL 2023 (GV2023)"
                : "VALUATION APPEAL BOARD: OUTCOME - APPEAL DECISIONS FOR THE GENERAL VALUATION ROLL 2023 (GV2023)";

            var kindShort = isReview ? "Section 52 Review" : "Appeal";

            var bodyIntro =
                "With reference to the above matter, I wish to advise that the Valuation Appeal Board for the property description below:";

            var resolvedLine = "Resolved inter alia as follows:";

            var dateText = ctx.LetterDate
                .ToDateTime(TimeOnly.MinValue)
                .ToString("dd MMMM yyyy", CultureInfo.InvariantCulture);

            var recipient = (model.ADDR1 ?? "").Trim();
            var greeting = string.IsNullOrWhiteSpace(recipient)
                ? "Dear Sir/Madam"
                : $"Dear {recipient}";

            var sigName = "VALUATION APPEAL BOARD";
            var sigOrg = "City of Johannesburg";
            var sigKey = (model.valuation_Key ?? "").Trim();

            return Document.Create(doc =>
            {
                doc.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.MarginLeft(30);
                    page.MarginRight(30);
                    page.MarginTop(10);
                    page.MarginBottom(10);

                    page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(11));

                    page.Footer().AlignCenter().Column(f =>
                    {
                        f.Item().PaddingTop(6).AlignCenter()
                            .Text("_______________________________________________")
                            .FontSize(7)
                            .FontColor(Colors.Grey.Darken2);

                        f.Item()
                            .Text("This is an official document generated by the City of Johannesburg Valuation Services Department")
                            .FontSize(7)
                            .AlignCenter()
                            .FontColor(Colors.Grey.Darken2);

                        f.Item()
                            .Text($"Generated on: {ctx.LetterDate:dd MMMM yyyy}")
                            .FontSize(7)
                            .AlignCenter()
                            .FontColor(Colors.Grey.Darken2);
                    });

                    page.Content().Column(col =>
                    {
                        // ✅ Preview banner like the others
                        if (isPreview)
                        {
                            col.Item()
                               .AlignCenter()
                               .Text("TEMPLATE PREVIEW (DUMMY DATA)")
                               .SemiBold()
                               .FontSize(10);

                            col.Item().PaddingTop(6);
                        }

                        if (File.Exists(headerPath))
                            col.Item().Height(85).AlignCenter().Image(headerPath, ImageScaling.FitArea);

                        // Address block + date
                        col.Item().PaddingTop(10).Row(r =>
                        {
                            r.RelativeItem().Column(left =>
                            {
                                AddLine(left, model.ADDR1);
                                AddLine(left, model.ADDR2);
                                AddLine(left, model.ADDR3);
                                AddLine(left, model.ADDR4);
                                AddLine(left, model.ADDR5);

                                left.Item().PaddingTop(8);

                                if (!string.IsNullOrWhiteSpace(model.Email))
                                    left.Item().Text(model.Email!).SemiBold();
                            });

                            r.ConstantItem(200).AlignRight().Text(dateText).SemiBold();
                        });

                        col.Item().PaddingTop(2)
                            .AlignCenter()
                            .Text($"GV2023 {kindShort.ToUpperInvariant()} NOTICE")
                            .SemiBold()
                            .FontSize(13);

                        col.Item().PaddingTop(8)
                            .AlignCenter()
                            .Text(title)
                            .Bold()
                            .FontSize(10);

                        col.Item().PaddingTop(6).LineHorizontal(1);

                        col.Item().PaddingTop(5).Text(greeting);

                        col.Item().PaddingTop(8).Text(bodyIntro).Justify();

                        col.Item().PaddingTop(10).Text(t =>
                        {
                            t.Span("Property Description: ").SemiBold();
                            t.Span(model.Property_desc ?? "");
                        });

                        // Property details table
                        col.Item().PaddingTop(8).Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(); // Suburb
                                c.RelativeColumn(); // ERF
                                c.RelativeColumn(); // Portion
                                c.RelativeColumn(); // RE
                                c.RelativeColumn(); // Objection
                                if (!isReview)
                                    c.RelativeColumn(); // Appeal No
                            });

                            HeaderCell(t, "SUBURB");
                            HeaderCell(t, "ERF NUMBER");
                            HeaderCell(t, "PORTION");
                            HeaderCell(t, "RE");
                            HeaderCell(t, "OBJECTION NO");
                            if (!isReview)
                                HeaderCell(t, "APPEAL NO");

                            BodyCell(t, model.Town);
                            BodyCell(t, model.ERF);
                            BodyCell(t, model.PTN);
                            BodyCell(t, model.RE);
                            BodyCell(t, model.Objection_No);
                            if (!isReview)
                                BodyCell(t, model.Appeal_No);
                        });

                        col.Item().PaddingTop(10).Text(resolvedLine).SemiBold();

                        // Resolved table
                        col.Item().PaddingTop(6).Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn();
                                c.RelativeColumn();
                                c.RelativeColumn();
                            });

                            HeaderCell(t, "Property Category");
                            HeaderCell(t, "Area/m²");
                            HeaderCell(t, "Market Value");

                            BodyCell(t, model.App_Category);
                            BodyCell(t, model.App_Extent?.ToString());
                            BodyCell(t, FormatRand(model.App_Market_Value));

                            BodyCell(t, "");
                            BodyCell(t, model.App_Extent2?.ToString());
                            BodyCell(t, FormatRand(model.App_Market_Value2));

                            BodyCell(t, "");
                            BodyCell(t, model.App_Extent3?.ToString());
                            BodyCell(t, FormatRand(model.App_Market_Value3));
                        });

                        col.Item().PaddingTop(10).Column(points =>
                        {
                            points.Item().Text("Please note the following:").SemiBold();

                            Bullet(points, "The decision will be adjusted accordingly to the implementation date being 1 July 2023.");
                            Bullet(points,
                                "The decision will reflect on your account within 30 days. Any adjustments to the account, if applicable, " +
                                "will be made by the Rates and Taxes Department in due course.");
                            Bullet(points,
                                "If you feel aggrieved by the above decision, you are entitled to take the matter on review to the " +
                                "High Court of South Africa at your own cost.");

                            points.Item().PaddingTop(12).Text("Regards,").SemiBold();
                        });

                        // Signature block
                        col.Item().PaddingTop(16).Column(sig =>
                        {
                            sig.Item().Text(sigName).SemiBold();
                            sig.Item().Text(sigOrg);

                            if (!string.IsNullOrWhiteSpace(sigKey))
                                sig.Item().PaddingTop(8).AlignRight().Text(sigKey).FontSize(11);
                        });
                    });
                });
            }).GeneratePdf();

            static void AddLine(ColumnDescriptor col, string? line)
            {
                if (!string.IsNullOrWhiteSpace(line))
                    col.Item().Text(line.Trim()).FontSize(11);
            }

            static IContainer CellBase(IContainer c) =>
                c.Border(1).PaddingVertical(4).PaddingHorizontal(6);

            static void HeaderCell(TableDescriptor t, string text)
            {
                t.Cell().Element(CellBase)
                    .Background(Colors.Grey.Lighten3)
                    .Text(text)
                    .Bold()
                    .FontSize(10);
            }

            static void BodyCell(TableDescriptor t, string? text)
            {
                t.Cell().Element(CellBase)
                    .Text((text ?? "").Trim())
                    .FontSize(10);
            }

            static void Bullet(ColumnDescriptor points, string text)
            {
                points.Item().PaddingTop(6).Row(r =>
                {
                    r.ConstantItem(12).Text("•");
                    r.RelativeItem().Text(text);
                });
            }

            static string FormatRand(object? value)
            {
                if (value is null) return "";

                if (value is decimal dec)
                    return "R " + dec.ToString("#,##0", CultureInfo.InvariantCulture);

                if (value is double dbl)
                    return "R " + Convert.ToDecimal(dbl).ToString("#,##0", CultureInfo.InvariantCulture);

                if (value is int i)
                    return "R " + i.ToString("#,##0", CultureInfo.InvariantCulture);

                if (value is long l)
                    return "R " + l.ToString("#,##0", CultureInfo.InvariantCulture);

                var raw = value.ToString()?.Trim() ?? "";
                if (raw.Length == 0) return "";

                if (raw.StartsWith("R", StringComparison.OrdinalIgnoreCase))
                {
                    var remainder = raw.Substring(1).Trim();

                    if (Regex.IsMatch(remainder, @"^\d{1,3}(,\d{3})+(\.\d+)?$"))
                        return "R " + remainder;

                    raw = remainder;
                }

                if (decimal.TryParse(raw,
                    NumberStyles.AllowThousands | NumberStyles.AllowDecimalPoint,
                    CultureInfo.InvariantCulture,
                    out var amount1))
                {
                    return "R " + amount1.ToString("#,##0", CultureInfo.InvariantCulture);
                }

                var cleaned = raw.Replace(" ", "").Replace(",", "");
                if (decimal.TryParse(cleaned,
                    NumberStyles.AllowDecimalPoint,
                    CultureInfo.InvariantCulture,
                    out var amount2))
                {
                    return "R " + amount2.ToString("#,##0", CultureInfo.InvariantCulture);
                }

                return "R " + raw;
            }
        }
    }
}

